// This file is autogenerated by the hyperschema compiler
// Schema Version: 1
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

import { c } from 'hyperschema/runtime'

const VERSION = 1

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @cero/invite
const encoding0 = {
  preencode(state, m) {
    c.uint.preencode(state, m.version)
    c.uint.preencode(state, m.expires)
    c.fixed32.preencode(state, m.key)
    c.fixed32.preencode(state, m.address)
    c.fixed32.preencode(state, m.seed)
    state.end++ // max flag is 1 so always one byte

    if (m.data) c.buffer.preencode(state, m.data)
  },
  encode(state, m) {
    const flags = m.data ? 1 : 0

    c.uint.encode(state, m.version)
    c.uint.encode(state, m.expires)
    c.fixed32.encode(state, m.key)
    c.fixed32.encode(state, m.address)
    c.fixed32.encode(state, m.seed)
    c.uint.encode(state, flags)

    if (m.data) c.buffer.encode(state, m.data)
  },
  decode(state) {
    const r0 = c.uint.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = c.fixed32.decode(state)
    const r3 = c.fixed32.decode(state)
    const r4 = c.fixed32.decode(state)
    const flags = c.uint.decode(state)

    return {
      version: r0,
      expires: r1,
      key: r2,
      address: r3,
      seed: r4,
      data: (flags & 1) !== 0 ? c.buffer.decode(state) : null
    }
  }
}

// @cero/join
const encoding1 = {
  preencode(state, m) {
    c.fixed32.preencode(state, m.invite)
    c.fixed32.preencode(state, m.reply)
    c.fixed64.preencode(state, m.proof)
    c.fixed32.preencode(state, m.identity)
    c.fixed64.preencode(state, m.signature)
    state.end++ // max flag is 1 so always one byte

    if (m.ts) c.uint.preencode(state, m.ts)
  },
  encode(state, m) {
    const flags = m.ts ? 1 : 0

    c.fixed32.encode(state, m.invite)
    c.fixed32.encode(state, m.reply)
    c.fixed64.encode(state, m.proof)
    c.fixed32.encode(state, m.identity)
    c.fixed64.encode(state, m.signature)
    c.uint.encode(state, flags)

    if (m.ts) c.uint.encode(state, m.ts)
  },
  decode(state) {
    const r0 = c.fixed32.decode(state)
    const r1 = c.fixed32.decode(state)
    const r2 = c.fixed64.decode(state)
    const r3 = c.fixed32.decode(state)
    const r4 = c.fixed64.decode(state)
    const flags = c.uint.decode(state)

    return {
      invite: r0,
      reply: r1,
      proof: r2,
      identity: r3,
      signature: r4,
      ts: (flags & 1) !== 0 ? c.uint.decode(state) : 0
    }
  }
}

// @cero/epoch
const encoding2 = {
  preencode(state, m) {
    c.uint.preencode(state, m.epoch)
    c.uint.preencode(state, m.stamp)
    c.fixed32.preencode(state, m.entropy)
  },
  encode(state, m) {
    c.uint.encode(state, m.epoch)
    c.uint.encode(state, m.stamp)
    c.fixed32.encode(state, m.entropy)
  },
  decode(state) {
    const r0 = c.uint.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = c.fixed32.decode(state)

    return {
      epoch: r0,
      stamp: r1,
      entropy: r2
    }
  }
}

// @cero/confirm.epochs
const encoding3_4 = c.array(encoding2)

// @cero/confirm
const encoding3 = {
  preencode(state, m) {
    c.uint.preencode(state, m.status)
    state.end++ // max flag is 8 so always one byte

    if (m.reason) c.string.preencode(state, m.reason)
    if (m.key) c.fixed32.preencode(state, m.key)
    if (m.encryptionKey) c.buffer.preencode(state, m.encryptionKey)
    if (m.epochs) encoding3_4.preencode(state, m.epochs)
  },
  encode(state, m) {
    const flags =
      (m.reason ? 1 : 0) | (m.key ? 2 : 0) | (m.encryptionKey ? 4 : 0) | (m.epochs ? 8 : 0)

    c.uint.encode(state, m.status)
    c.uint.encode(state, flags)

    if (m.reason) c.string.encode(state, m.reason)
    if (m.key) c.fixed32.encode(state, m.key)
    if (m.encryptionKey) c.buffer.encode(state, m.encryptionKey)
    if (m.epochs) encoding3_4.encode(state, m.epochs)
  },
  decode(state) {
    const r0 = c.uint.decode(state)
    const flags = c.uint.decode(state)

    return {
      status: r0,
      reason: (flags & 1) !== 0 ? c.string.decode(state) : null,
      key: (flags & 2) !== 0 ? c.fixed32.decode(state) : null,
      encryptionKey: (flags & 4) !== 0 ? c.buffer.decode(state) : null,
      epochs: (flags & 8) !== 0 ? encoding3_4.decode(state) : null
    }
  }
}

// @cero/rows.data
const encoding4_0 = c.array(c.buffer)

// @cero/rows
const encoding4 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.data) encoding4_0.preencode(state, m.data)
  },
  encode(state, m) {
    const flags = m.data ? 1 : 0

    c.uint.encode(state, flags)

    if (m.data) encoding4_0.encode(state, m.data)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      data: (flags & 1) !== 0 ? encoding4_0.decode(state) : null
    }
  }
}

// @cero/changes.prev
const encoding5_0 = encoding4_0
// @cero/changes.next
const encoding5_1 = encoding4_0

// @cero/changes
const encoding5 = {
  preencode(state, m) {
    state.end++ // max flag is 2 so always one byte

    if (m.prev) encoding5_0.preencode(state, m.prev)
    if (m.next) encoding5_1.preencode(state, m.next)
  },
  encode(state, m) {
    const flags = (m.prev ? 1 : 0) | (m.next ? 2 : 0)

    c.uint.encode(state, flags)

    if (m.prev) encoding5_0.encode(state, m.prev)
    if (m.next) encoding5_1.encode(state, m.next)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      prev: (flags & 1) !== 0 ? encoding5_0.decode(state) : null,
      next: (flags & 2) !== 0 ? encoding5_1.decode(state) : null
    }
  }
}

// @cero/query
const encoding6 = {
  preencode(state, m) {
    state.end++ // max flag is 64 so always one byte

    if (m.gt) c.string.preencode(state, m.gt)
    if (m.gte) c.string.preencode(state, m.gte)
    if (m.lt) c.string.preencode(state, m.lt)
    if (m.lte) c.string.preencode(state, m.lte)
    if (m.limit) c.uint.preencode(state, m.limit)
    if (m.data) c.json.preencode(state, m.data)
  },
  encode(state, m) {
    const flags =
      (m.gt ? 1 : 0) |
      (m.gte ? 2 : 0) |
      (m.lt ? 4 : 0) |
      (m.lte ? 8 : 0) |
      (m.limit ? 16 : 0) |
      (m.reverse ? 32 : 0) |
      (m.data ? 64 : 0)

    c.uint.encode(state, flags)

    if (m.gt) c.string.encode(state, m.gt)
    if (m.gte) c.string.encode(state, m.gte)
    if (m.lt) c.string.encode(state, m.lt)
    if (m.lte) c.string.encode(state, m.lte)
    if (m.limit) c.uint.encode(state, m.limit)
    if (m.data) c.json.encode(state, m.data)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      gt: (flags & 1) !== 0 ? c.string.decode(state) : null,
      gte: (flags & 2) !== 0 ? c.string.decode(state) : null,
      lt: (flags & 4) !== 0 ? c.string.decode(state) : null,
      lte: (flags & 8) !== 0 ? c.string.decode(state) : null,
      limit: (flags & 16) !== 0 ? c.uint.decode(state) : 0,
      reverse: (flags & 32) !== 0,
      data: (flags & 64) !== 0 ? c.json.decode(state) : null
    }
  }
}

// @cero/create
const encoding7 = {
  preencode(state, m) {
    state.end++ // max flag is 2 so always one byte

    if (m.id) c.string.preencode(state, m.id)
    if (m.name) c.string.preencode(state, m.name)
  },
  encode(state, m) {
    const flags = (m.id ? 1 : 0) | (m.name ? 2 : 0)

    c.uint.encode(state, flags)

    if (m.id) c.string.encode(state, m.id)
    if (m.name) c.string.encode(state, m.name)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      id: (flags & 1) !== 0 ? c.string.decode(state) : null,
      name: (flags & 2) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @cero/blob-id
const encoding8 = {
  preencode(state, m) {
    c.fixed32.preencode(state, m.coreKey)
    c.uint.preencode(state, m.blockOffset)
    c.uint.preencode(state, m.blockLength)
    c.uint.preencode(state, m.byteOffset)
    c.uint.preencode(state, m.byteLength)
    c.string.preencode(state, m.type)
  },
  encode(state, m) {
    c.fixed32.encode(state, m.coreKey)
    c.uint.encode(state, m.blockOffset)
    c.uint.encode(state, m.blockLength)
    c.uint.encode(state, m.byteOffset)
    c.uint.encode(state, m.byteLength)
    c.string.encode(state, m.type)
  },
  decode(state) {
    const r0 = c.fixed32.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = c.uint.decode(state)
    const r3 = c.uint.decode(state)
    const r4 = c.uint.decode(state)
    const r5 = c.string.decode(state)

    return {
      coreKey: r0,
      blockOffset: r1,
      blockLength: r2,
      byteOffset: r3,
      byteLength: r4,
      type: r5
    }
  }
}

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@cero/invite':
      return encoding0
    case '@cero/join':
      return encoding1
    case '@cero/epoch':
      return encoding2
    case '@cero/confirm':
      return encoding3
    case '@cero/rows':
      return encoding4
    case '@cero/changes':
      return encoding5
    case '@cero/query':
      return encoding6
    case '@cero/create':
      return encoding7
    case '@cero/blob-id':
      return encoding8
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

export { resolveStruct, getStruct, getEnum, getEncoding, encode, decode, setVersion, version }
