// This file is autogenerated by the hyperschema compiler
// Schema Version: 2
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

import { c } from 'hyperschema/runtime'

const VERSION = 2

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @cero/invite-body
const encoding0 = {
  preencode(state, m) {
    c.uint.preencode(state, m.version)
    c.fixed32.preencode(state, m.publicKey)
    c.string.preencode(state, m.role)
    c.uint.preencode(state, m.expires)
    state.end++ // max flag is 1 so always one byte

    if (m.data) c.buffer.preencode(state, m.data)
    c.buffer.preencode(state, m.blind)
  },
  encode(state, m) {
    const flags = m.data ? 1 : 0

    c.uint.encode(state, m.version)
    c.fixed32.encode(state, m.publicKey)
    c.string.encode(state, m.role)
    c.uint.encode(state, m.expires)
    c.uint.encode(state, flags)

    if (m.data) c.buffer.encode(state, m.data)
    c.buffer.encode(state, m.blind)
  },
  decode(state) {
    const r0 = c.uint.decode(state)
    const r1 = c.fixed32.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.uint.decode(state)
    const flags = c.uint.decode(state)

    return {
      version: r0,
      publicKey: r1,
      role: r2,
      expires: r3,
      data: (flags & 1) !== 0 ? c.buffer.decode(state) : null,
      blind: c.buffer.decode(state)
    }
  }
}

// @cero/invite
const encoding1 = {
  preencode(state, m) {
    c.uint.preencode(state, m.version)
    c.fixed32.preencode(state, m.publicKey)
    c.string.preencode(state, m.role)
    c.uint.preencode(state, m.expires)
    state.end++ // max flag is 1 so always one byte

    if (m.data) c.buffer.preencode(state, m.data)
    c.buffer.preencode(state, m.blind)
    c.fixed64.preencode(state, m.sig)
  },
  encode(state, m) {
    const flags = m.data ? 1 : 0

    c.uint.encode(state, m.version)
    c.fixed32.encode(state, m.publicKey)
    c.string.encode(state, m.role)
    c.uint.encode(state, m.expires)
    c.uint.encode(state, flags)

    if (m.data) c.buffer.encode(state, m.data)
    c.buffer.encode(state, m.blind)
    c.fixed64.encode(state, m.sig)
  },
  decode(state) {
    const r0 = c.uint.decode(state)
    const r1 = c.fixed32.decode(state)
    const r2 = c.string.decode(state)
    const r3 = c.uint.decode(state)
    const flags = c.uint.decode(state)

    return {
      version: r0,
      publicKey: r1,
      role: r2,
      expires: r3,
      data: (flags & 1) !== 0 ? c.buffer.decode(state) : null,
      blind: c.buffer.decode(state),
      sig: c.fixed64.decode(state)
    }
  }
}

// @cero/confirm
const encoding2 = {
  preencode(state, m) {
    c.uint.preencode(state, m.status)
    state.end++ // max flag is 8 so always one byte

    if (m.reason) c.string.preencode(state, m.reason)
    if (m.key) c.fixed32.preencode(state, m.key)
    if (m.encryptionKey) c.buffer.preencode(state, m.encryptionKey)
    if (m.extra) c.buffer.preencode(state, m.extra)
  },
  encode(state, m) {
    const flags =
      (m.reason ? 1 : 0) | (m.key ? 2 : 0) | (m.encryptionKey ? 4 : 0) | (m.extra ? 8 : 0)

    c.uint.encode(state, m.status)
    c.uint.encode(state, flags)

    if (m.reason) c.string.encode(state, m.reason)
    if (m.key) c.fixed32.encode(state, m.key)
    if (m.encryptionKey) c.buffer.encode(state, m.encryptionKey)
    if (m.extra) c.buffer.encode(state, m.extra)
  },
  decode(state) {
    const r0 = c.uint.decode(state)
    const flags = c.uint.decode(state)

    return {
      status: r0,
      reason: (flags & 1) !== 0 ? c.string.decode(state) : null,
      key: (flags & 2) !== 0 ? c.fixed32.decode(state) : null,
      encryptionKey: (flags & 4) !== 0 ? c.buffer.decode(state) : null,
      extra: (flags & 8) !== 0 ? c.buffer.decode(state) : null
    }
  }
}

// @cero/rows.data
const encoding3_0 = c.array(c.buffer)

// @cero/rows
const encoding3 = {
  preencode(state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.data) encoding3_0.preencode(state, m.data)
  },
  encode(state, m) {
    const flags = m.data ? 1 : 0

    c.uint.encode(state, flags)

    if (m.data) encoding3_0.encode(state, m.data)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      data: (flags & 1) !== 0 ? encoding3_0.decode(state) : null
    }
  }
}

// @cero/query
const encoding4 = {
  preencode(state, m) {
    state.end++ // max flag is 64 so always one byte

    if (m.gt) c.string.preencode(state, m.gt)
    if (m.gte) c.string.preencode(state, m.gte)
    if (m.lt) c.string.preencode(state, m.lt)
    if (m.lte) c.string.preencode(state, m.lte)
    if (m.limit) c.uint.preencode(state, m.limit)
    if (m.data) c.json.preencode(state, m.data)
  },
  encode(state, m) {
    const flags =
      (m.gt ? 1 : 0) |
      (m.gte ? 2 : 0) |
      (m.lt ? 4 : 0) |
      (m.lte ? 8 : 0) |
      (m.limit ? 16 : 0) |
      (m.reverse ? 32 : 0) |
      (m.data ? 64 : 0)

    c.uint.encode(state, flags)

    if (m.gt) c.string.encode(state, m.gt)
    if (m.gte) c.string.encode(state, m.gte)
    if (m.lt) c.string.encode(state, m.lt)
    if (m.lte) c.string.encode(state, m.lte)
    if (m.limit) c.uint.encode(state, m.limit)
    if (m.data) c.json.encode(state, m.data)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      gt: (flags & 1) !== 0 ? c.string.decode(state) : null,
      gte: (flags & 2) !== 0 ? c.string.decode(state) : null,
      lt: (flags & 4) !== 0 ? c.string.decode(state) : null,
      lte: (flags & 8) !== 0 ? c.string.decode(state) : null,
      limit: (flags & 16) !== 0 ? c.uint.decode(state) : 0,
      reverse: (flags & 32) !== 0,
      data: (flags & 64) !== 0 ? c.json.decode(state) : null
    }
  }
}

// @cero/create
const encoding5 = {
  preencode(state, m) {
    state.end++ // max flag is 8 so always one byte

    if (m.id) c.string.preencode(state, m.id)
    if (m.name) c.string.preencode(state, m.name)
    if (m.role) c.string.preencode(state, m.role)
  },
  encode(state, m) {
    const flags = (m.id ? 1 : 0) | (m.name ? 2 : 0) | (m.role ? 4 : 0) | (m.noAccept ? 8 : 0)

    c.uint.encode(state, flags)

    if (m.id) c.string.encode(state, m.id)
    if (m.name) c.string.encode(state, m.name)
    if (m.role) c.string.encode(state, m.role)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      id: (flags & 1) !== 0 ? c.string.decode(state) : null,
      name: (flags & 2) !== 0 ? c.string.decode(state) : null,
      role: (flags & 4) !== 0 ? c.string.decode(state) : null,
      noAccept: (flags & 8) !== 0
    }
  }
}

// @cero/blob-id
const encoding6 = {
  preencode(state, m) {
    c.fixed32.preencode(state, m.coreKey)
    c.uint.preencode(state, m.blockOffset)
    c.uint.preencode(state, m.blockLength)
    c.uint.preencode(state, m.byteOffset)
    c.uint.preencode(state, m.byteLength)
    c.string.preencode(state, m.type)
  },
  encode(state, m) {
    c.fixed32.encode(state, m.coreKey)
    c.uint.encode(state, m.blockOffset)
    c.uint.encode(state, m.blockLength)
    c.uint.encode(state, m.byteOffset)
    c.uint.encode(state, m.byteLength)
    c.string.encode(state, m.type)
  },
  decode(state) {
    const r0 = c.fixed32.decode(state)
    const r1 = c.uint.decode(state)
    const r2 = c.uint.decode(state)
    const r3 = c.uint.decode(state)
    const r4 = c.uint.decode(state)
    const r5 = c.string.decode(state)

    return {
      coreKey: r0,
      blockOffset: r1,
      blockLength: r2,
      byteOffset: r3,
      byteLength: r4,
      type: r5
    }
  }
}

// @cero/changes.prev
const encoding7_0 = encoding3_0
// @cero/changes.next
const encoding7_1 = encoding3_0

// @cero/changes
const encoding7 = {
  preencode(state, m) {
    state.end++ // max flag is 2 so always one byte

    if (version >= 2 && m.prev) encoding7_0.preencode(state, m.prev)
    if (version >= 2 && m.next) encoding7_1.preencode(state, m.next)
  },
  encode(state, m) {
    const flags = ((version >= 2 && m.prev) ? 1 : 0) | ((version >= 2 && m.next) ? 2 : 0)

    c.uint.encode(state, flags)

    if (version >= 2 && m.prev) encoding7_0.encode(state, m.prev)
    if (version >= 2 && m.next) encoding7_1.encode(state, m.next)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      prev: (version >= 2 && (flags & 1) !== 0) ? encoding7_0.decode(state) : null,
      next: (version >= 2 && (flags & 2) !== 0) ? encoding7_1.decode(state) : null
    }
  }
}

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@cero/invite-body':
      return encoding0
    case '@cero/invite':
      return encoding1
    case '@cero/confirm':
      return encoding2
    case '@cero/rows':
      return encoding3
    case '@cero/query':
      return encoding4
    case '@cero/create':
      return encoding5
    case '@cero/blob-id':
      return encoding6
    case '@cero/changes':
      return encoding7
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

export { resolveStruct, getStruct, getEnum, getEncoding, encode, decode, setVersion, version }
