export declare const SINGLE = "single";
export declare const COLLECTION = "collection";
export declare const HANDLE = "handle";
export declare const ACTION = "action";
export declare const ACTIVE = "active";
export declare const PASSIVE = "passive";
export declare const ROCKS = "rocks";
export declare const BEE = "bee";
export declare const OWNER = "owner";
export declare const ADMIN = "admin";
export declare const MEMBER = "member";
export declare const READER = "reader";
export declare const READ = "read";
export declare const WRITE = "write";
export declare const DELETE = "delete";
export declare const INVITE = "invite";
export declare const REMOVE = "remove";
export declare const ASSIGN = "assign";
export declare const ROLE_PERMS: {
    owner: string[];
    admin: string[];
    member: string[];
    reader: string[];
};
export declare const RANK: {
    owner: number;
    admin: number;
    member: number;
    reader: number;
};
export declare const NAMESPACE = "cero";
export declare const QUERY_RESERVED: Set<string>;
export declare const COUNTERS = "counters";
export declare const EPOCHS = "epochs";
